CREATE SEQUENCE  "CMS"."CMS_TASK_MASTER_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10322 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

-- table name: CMS_TASK_MASTER
  CREATE TABLE "CMS"."CMS_TASK_MASTER" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"TASK_NAME" VARCHAR2(100 BYTE), 
	"TEXT" NVARCHAR2(100), 
	"URL" VARCHAR2(100 BYTE), 
	"PARENTID" NUMBER(38,0), 
	"CREATE_BY" VARCHAR2(30 BYTE), 
	"CREATE_DATE" DATE, 
	"FOR_ALL" VARCHAR2(1 BYTE), 
	"ORDER_COL" NUMBER(38,0), 
	"ICON" NVARCHAR2(50), 
	"UPDATE_BY" NVARCHAR2(50), 
	"UPDATE_DATE" DATE, 
	"PARENT_CLASS" VARCHAR2(100 BYTE), 
	"HASCHILD" NUMBER(*,0) DEFAULT 0, 
	 CONSTRAINT "CMS_TASK_MASTER_PK" PRIMARY KEY ("ID")
   )

   -- trigger for auto increment

create or replace TRIGGER "CMS"."AUTOID_CMS_TASK_MASTER" 
BEFORE INSERT
ON CMS.CMS_TASK_MASTER 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;

   SELECT CMS_TASK_MASTER_SEQ.NEXTVAL INTO tmpVar FROM dual;
   :NEW.ID := tmpVar;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END AUTOID_CMS_TASK_MASTER;