CREATE SEQUENCE  "CMS"."CMS_TASK_ACTION_DETAILS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10322 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

-- table name: CMS_TASK_ACTION_DETAILS
CREATE TABLE "CMS"."CMS_TASK_ACTION_DETAILS" 
   (	 
	"TASK_ID" NUMBER(50 BYTE), 
	"ACTION_ID" NUMBER(10 BYTE), 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(30 BYTE), 
	"UPDATE_DATE" DATE, 
	  CONSTRAINT "CMS_TASK_ACTION_DETAILS_PK" PRIMARY KEY ("TASK_ID","ACTION_ID"),
	 CONSTRAINT "CMS_TASK_ACTION_DETAILS_TASK_ID_FK" FOREIGN KEY("TASK_ID")   REFERENCES "CMS"."CMS_TASK_MASTER"("ID") ON DELETE CASCADE, 
	 CONSTRAINT "CMS_TASK_ACTION_DETAILS_ACTION_ID_FK" FOREIGN KEY("ACTION_ID")   REFERENCES "CMS"."CMS_ACTION_MASTER"("ID") ON DELETE CASCADE 
	 
   )

   -- trigger for auto increment

create or replace TRIGGER "CMS"."AUTOID_CMS_TASK_ACTION_DETAILS" 
BEFORE INSERT
ON CMS.CMS_TASK_ACTION_DETAILS 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;

   SELECT CMS_TASK_ACTION_DETAILS_SEQ.NEXTVAL INTO tmpVar FROM dual;
   :NEW.ID := tmpVar;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END AUTOID_CMS_TASK_ACTION_DETAILS;