CREATE SEQUENCE  "CMS"."CMS_ACTION_MASTER_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10322 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

-- table
   CREATE TABLE "CMS"."CMS_ACTION_MASTER" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ACTION_NAME" NVARCHAR2(50) NOT NULL ENABLE, 
	"DESCRIPTION" NVARCHAR2(200), 
	"CREATE_BY" VARCHAR2(30 BYTE), 
	"CREATE_DATE" DATE DEFAULT NULL, 
	"UPDATE_BY" VARCHAR2(50 BYTE), 
	"UPDATE_DATE" DATE, 
	"PRIORITY" NUMBER(*,0), 
	 CONSTRAINT "CMS_ACTION_MASTER_PK" PRIMARY KEY ("ID")
   )

   create or replace TRIGGER "CMS"."AUTOID_CMS_ACTION_MASTER" 
BEFORE INSERT
ON CMS.CMS_ACTION_MASTER 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;

   SELECT CMS_ACTION_MASTER_SEQ.NEXTVAL INTO tmpVar FROM dual;
   :NEW.ID := tmpVar;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END AUTOID_CMS_ACTION_MASTER;