  CREATE TABLE "CMS"."CMS_USERDETAILS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"USER_NAME" NVARCHAR2(100) NOT NULL ENABLE, 
	"USER_PASSWORD" NVARCHAR2(250) NOT NULL ENABLE, 
	"MOBILE" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"CREATEBY" NVARCHAR2(30), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATEBY" NVARCHAR2(30), 
	"UPDATEDATE" DATE, 
	"STATUS" VARCHAR2(10 BYTE), 
	"ROLE_ID" NUMBER NOT NULL ENABLE, 
	"LOCATIONCODE" VARCHAR2(5 CHAR), 
	"INVOICENO" NUMBER, 
	"CD" NUMBER, 
	"BILLCYCLE" NUMBER, 
	 CONSTRAINT "CMS_USERDETAILS_PK" PRIMARY KEY ("ID"),
	  CONSTRAINT "CMS_USERDETAILS_ROLE_ID_FK" FOREIGN KEY("ROLE_ID")  REFERENCES "CMS"."CMS_ROLE_MASTER"("ID"),
   )
   
    CREATE TABLE "CMS"."CMS_TASK_MASTER" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"TASK_NAME" VARCHAR2(100 BYTE), 
	"TEXT" NVARCHAR2(100), 
	"URL" VARCHAR2(100 BYTE), 
	"PARENTID" NUMBER(38,0), 
	"CREATE_BY" VARCHAR2(30 BYTE), 
	"CREATE_DATE" DATE, 
	"FOR_ALL" VARCHAR2(1 BYTE), 
	"ORDER_COL" NUMBER(38,0), 
	"ICON" NVARCHAR2(50), 
	"UPDATE_BY" NVARCHAR2(50), 
	"UPDATE_DATE" DATE, 
	"PARENT_CLASS" VARCHAR2(100 BYTE), 
	"HASCHILD" NUMBER(*,0) DEFAULT 0, 
	 CONSTRAINT "CMS_TASK_MASTER_PK" PRIMARY KEY ("ID")
   )
    CREATE TABLE "CMS"."CMS_ROLE_MASTER" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ROLE_NAME" NVARCHAR2(50) NOT NULL ENABLE, 
	"DESCRIPTION" NVARCHAR2(200), 
	"CREATE_BY" VARCHAR2(30 BYTE), 
	"CREATE_DATE" DATE DEFAULT NULL, 
	"UPDATE_BY" VARCHAR2(50 BYTE), 
	"UPDATE_DATE" DATE, 
	"PRIORITY" NUMBER(*,0), 
	 CONSTRAINT "CMS_ROLE_MASTER_PK" PRIMARY KEY ("ID")
   )
   
   CREATE TABLE "CMS"."CMS_ROLE_TASK_DETAILS" 
   (
	"ROLE_ID" NUMBER(P), 
	"TASK_ID" NUMBER(P), 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(30 BYTE), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "CMS_ROLE_TASK_DETAILS_PK" PRIMARY KEY ("ROLE_ID","TASK_ID"),
	 CONSTRAINT "CMS_ROLE_TASK_DETAILS_ROLE_ID_FK" FOREIGN KEY("ROLE_ID")   REFERENCES "CMS"."CMS_ROLE_MASTER"("ID"),  
	 CONSTRAINT "CMS_ROLE_TASK_DETAILS_TASK_ID_FK" FOREIGN KEY("TASK_ID")   REFERENCES "CMS"."CMS_TASK_MASTER"("ID")  
   )
   
    CREATE TABLE "CMS"."CMS_ACTION_MASTER" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ACTION_NAME" NVARCHAR2(50) NOT NULL ENABLE, 
	"DESCRIPTION" NVARCHAR2(200), 
	"CREATE_BY" VARCHAR2(30 BYTE), 
	"CREATE_DATE" DATE DEFAULT NULL, 
	"UPDATE_BY" VARCHAR2(50 BYTE), 
	"UPDATE_DATE" DATE, 
	"PRIORITY" NUMBER(*,0), 
	 CONSTRAINT "CMS_ACTION_MASTER_PK" PRIMARY KEY ("ID")
   )
   
   CREATE TABLE "CMS"."CMS_TASK_ACTION_DETAILS" 
   (	 
	"TASK_ID" NUMBER(50 BYTE), 
	"ACTION_ID" NUMBER(10 BYTE), 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(30 BYTE), 
	"UPDATE_DATE" DATE, 
	  CONSTRAINT "CMS_TASK_ACTION_DETAILS_PK" PRIMARY KEY ("TASK_ID","ACTION_ID"),
	 CONSTRAINT "CMS_TASK_ACTION_DETAILS_TASK_ID_FK" FOREIGN KEY("TASK_ID")   REFERENCES "CMS"."CMS_TASK_MASTER"("ID"), 
	 CONSTRAINT "CMS_TASK_ACTION_DETAILS_ACTION_ID_FK" FOREIGN KEY("ACTION_ID")   REFERENCES "CMS"."CMS_ACTION_MASTER"("ID") 
   )