--------------------------------------------------------
--  File created - Tuesday-September-14-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BC_MUNICIPAL_DIVISION
--------------------------------------------------------

  CREATE TABLE "NEBCWEB"."BC_MUNICIPAL_DIVISION" 
   (	"ID" NUMBER(*,0), 
	"CIRCLE_ID" NUMBER(*,0), 
	"NAME" NVARCHAR2(200), 
	"NAMEBN" NVARCHAR2(200), 
	"LOCATION_CODE" NVARCHAR2(10), 
	"LOCATION_ID" NUMBER(*,0), 
	"ISBANGLAREPORT" NUMBER(1,0) DEFAULT 0, 
	"ISCITYCORPORATION" NUMBER(1,0) DEFAULT 0, 
	"ISMUNICIPAL" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into NEBCWEB.BC_MUNICIPAL_DIVISION
SET DEFINE OFF;
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (1,1,'S & D Hathazari, Ctg.','????????? ??????','N2',102,1,0,0);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (2,1,'S & D MOHRA, Ctg.','??&?? ?????, ?????????','N3',103,1,0,0);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (3,1,'S & D Barabkunda, Ctg.','??&?? ????????, ?????????','N4',104,1,0,0);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (4,1,null,null,'N5',161,1,0,0);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (5,2,'Dist. Div. Patiya','?????? ??????','S1',114,1,0,0);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (6,2,'Dist. Div. Coxs Bazar','????????? ??????','S2',115,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (7,2,'Satkania Electric Supply','?????????? ????????? ??????','S3',116,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (8,2,'Dohazari Electric Supply','???????? ????????? ??????','S4',117,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (9,2,null,null,'S5',118,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (10,2,'Lama Electric Supply','???? ????????? ??????','S6',119,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (11,3,'S & D Patharghata, Ctg.','???????? ??????','E1',1,1,1,0);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (12,3,'S & D Stadium, Ctg.','??&?? ??????????, ?????????','E2',96,1,1,0);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (13,3,'S & D Sholoshahar, Ctg.','??&?? ?????????, ?????????','E3',97,1,1,0);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (14,3,'S & D Kalurghat, Ctg.','??&?? ????????, ?????????','E4',98,1,1,0);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (15,3,'S & D BAKULIA','??&?? ????????','E5',99,1,1,0);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (16,3,'S & D Madarbari, Ctg','??&?? ??????????, ?????????','E6',100,1,1,0);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (17,4,'S & D Agrabad , Ctg.','??&?? ????????, ?????????','W1',123,1,1,0);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (18,4,'S & D Halishahar, Ctg.','??&?? ???????, ?????????','W2',124,1,1,0);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (19,4,'S & D Pahartali, Ctg','??&?? ?????????, ?????????','W3',125,1,1,0);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (20,4,'S & D Kulshi, Ctg.','??&?? ?????, ?????????','W4',126,1,1,0);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (21,4,'S & D Rampur, Ctg.','??&?? ??????, ?????????','W5',127,1,1,0);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (22,4,'S & D Newmooring, Ctg','??&?? ????????, ?????????','W6',128,1,1,0);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (23,5,'Dist.Div.Rangamati','?????????? ??????','R1',105,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (24,5,'Dist. Div. Banderban','????????? ??????','R2',106,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (25,5,' Ramgarh Electric Supply','??????  ??????','R6',110,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (26,5,'Matiranga Elec. Supply','?????????? ??????','R8',112,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (27,5,null,null,'RM',130,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (28,6,'S & D I,Comilla','??&??-? (????????)','C1',30,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (29,6,'S & D II,Comilla','??&??-? (????????)','C2',31,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (30,6,'S&D-1, B.Baria','??&??-? (??.??????)','C3',32,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (31,6,'S & D Chandpur','??????? ??????','C6',33,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (32,6,'S & D Comilla-3','??&?? ????????-?','C7',34,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (33,6,'S&D-2, B.Baria','??&??-? (??.??????)','C8',181,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (34,6,'S & D, Daulatganj','???????? ??????','D2',36,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (35,6,'ESU, Chaddagram','?????????? ??????','D3',37,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (36,7,'Dist. Feni','???? ??????','B1',24,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (37,7,'Dist. Maijdee','?????? ??????','B2',25,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (38,7,'S & D, Chaumuhini','??????? ??????','B5',26,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (39,7,'S & D, Laxmipur','?????????? ??????','B6',27,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (40,8,'S&D Div -1,BPDB,Sylhet','??&?? ????? -? (?????)','H1',85,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (41,8,'S&D Div -2,BPDB,Sylhet','??&?? ?????-? (?????)','H2',86,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (42,8,'S&D Div -3,BPDB,Sylhet','??&?? ?????-? (?????)','H3',87,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (43,8,'S & D Div - 4','??&?? ?????-? (?????)','H7',88,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (44,8,'DEARI ESU','????? ??????','G2',81,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (45,8,'SUNAMGONG ESU','????????? ??????','G7',84,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (46,9,'Hobigonj S&D','??????? ??????','H4',55,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (47,9,'KULAURA S&D ','???????? ??????','H5',56,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (48,9,'Moulvibazar D&D','?????????? ??????','H6',57,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (49,9,'JAGANNATHPUR ESU','?????????? ??????','G5',82,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (50,10,'S&D-1(NORTH)','??&??-? (?????)','M1',67,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (51,10,'S&D-2 (SOUTH)','??&??-? (??????)','M2',68,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (52,10,'S&D Netrokona','????????? ??????','M3',69,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (53,10,'Ishwarganj ESU.','????????? ??????','M5',71,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (54,10,'GOURIPUR ESU.','??????? ??????','M7',73,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (55,10,'S&D FULPUR','?????? ??????','M8',74,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (56,10,'Fulbaria ESU.','??????????? ??????','M9',75,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (57,10,'Bajitpur','???????? ??????','K1',50,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (58,10,'S & D Bhairab Bazar','???? ????? ??????','K2',51,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (59,10,'Kishoreganj Pourashava','????????? ??????','K3',52,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (60,10,'Kuliarchar Pouroshova','????????? ??????','K4',53,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (61,10,'S&D BHALUKA','?????? ??????','K6',64,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (62,10,'S&D Gaffargaon.','??????? ??????','K7',65,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (63,10,'S&D TRISHAL','??????? ??????','K8',66,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (64,10,'Nalitabari','??????????? ??????','J2',59,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (65,10,'Nokhla','???? ??????','J3',60,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (66,10,'S&D Sherpur','?????? ??????','J4',61,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (67,10,'Sreebordi','???????? ??????','J5',62,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (68,11,'S & D-1 TANGAIL','??&??-? (???????)','T1',89,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (69,11,'S & D Bhuapur','??????? ??????','T2',90,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (70,11,'S & D Ghatai','?????? ??????','T3',91,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (71,11,'S & D-2 TANGAIL','??&??-? (???????)','T4',92,1,1,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (72,11,'S & D Kalihati','???????? ??????','T5',93,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (73,11,'S & D Shakhipur','?????? ??????','T6',94,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (74,11,'Jamalpur','???????? ??????','J6',48,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (75,11,'Sarishabari','?????????? ??????','J7',49,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (76,2,'Chokoria Electric Supply','???????? ??????','S7',120,1,0,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (77,10,'S&D-3 MYMENSINGH ','??&??-? ?????????','J8',63,1,1,1);
Insert into NEBCWEB.BC_MUNICIPAL_DIVISION (ID,CIRCLE_ID,NAME,NAMEBN,LOCATION_CODE,LOCATION_ID,ISBANGLAREPORT,ISCITYCORPORATION,ISMUNICIPAL) values (78,10,'Muktagacha ESU.','?????????? ??????','M4',70,1,0,1);
--------------------------------------------------------
--  DDL for Index BC_MUNICIPAL_DIVISION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEBCWEB"."BC_MUNICIPAL_DIVISION_PK" ON "NEBCWEB"."BC_MUNICIPAL_DIVISION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BC_MUNICIPAL_DIVISION
--------------------------------------------------------

  ALTER TABLE "NEBCWEB"."BC_MUNICIPAL_DIVISION" ADD CONSTRAINT "BC_MUNICIPAL_DIVISION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "NEBCWEB"."BC_MUNICIPAL_DIVISION" MODIFY ("CIRCLE_ID" NOT NULL ENABLE);
  ALTER TABLE "NEBCWEB"."BC_MUNICIPAL_DIVISION" MODIFY ("ID" NOT NULL ENABLE);
